backend/modules/admin/models/BizRule.php
<?php

namespace backend\modules\admin\models;

use Yii;
use yii\rbac\Rule;
use backend\modules\admin\components\Configs;

/**
 * BizRule
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class BizRule extends \yii\base\Model
{
    /**
     * @var string name of the rule
     */
    public $name;

    /**
     * @var integer UNIX timestamp representing the rule creation time
     */
    public $createdAt;

    /**
     * @var integer UNIX timestamp representing the rule updating time
     */
    public $updatedAt;

    /**
     * @var string Rule classname.
     */
    public $className;

    /**
     * @var Rule
     */
    private $_item;

    /**
     * Initilaize object
     * @param \yii\rbac\Rule $item
     * @param array $config
     */
    public function __construct($item, $config = [])
    {
        $this->_item = $item;
        if ($item !== null) {
            $this->name = $item->name;
            $this->className = get_class($item);
        }
        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'className'], 'required'],
            [['className'], 'string'],
            [['className'], 'classExists']
        ];
    }

    /**
     * Validate class exists
     */
    public function classExists()
    {
        if (!class_exists($this->className)) {
            $message = Yii::t('rbac-admin', 'Unknown_class', ['class' => $this->className]);
            $this->addError('className', $message);
            return;
        }
        if (!is_subclass_of($this->className, Rule::className())) {
            $message = Yii::t('rbac-admin', 'CLASS_MUST_EXTEND_RULE', [
                    'class' => $this->className]);
            $this->addError('className', $message);
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('rbac-admin', 'NAME'),
            'className' => Yii::t('rbac-admin', 'CLASS_NAME'),
        ];
    }

    /**
     * Check if new record.
     * @return boolean
     */
    public function getIsNewRecord()
    {
        return $this->_item === null;
    }

    /**
     * Find model by id
     * @param type $id
     * @return null|static
     */
    public static function find($id)
    {
        $item = Configs::authManager()->getRule($id);
        if ($item !== null) {
            return new static($item);
        }

        return null;
    }

    /**
     * Save model to authManager
     * @return boolean
     */
    public function save()
    {
        if ($this->validate()) {
            $manager = Configs::authManager();
            $class = $this->className;
            if ($this->_item === null) {
                $this->_item = new $class();
                $isNew = true;
            } else {
                $isNew = false;
                $oldName = $this->_item->name;
            }
            $this->_item->name = $this->name;

            if ($isNew) {
                $manager->add($this->_item);
            } else {
                $manager->update($oldName, $this->_item);
            }

            return true;
        } else {
            return false;
        }
    }

    /**
     * Get item
     * @return Item
     */
    public function getItem()
    {
        return $this->_item;
    }
}

backend/modules/admin/models/User.php
<?php

namespace backend\modules\admin\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use common\models\Member;
use backend\models\Admin;
use backend\modules\admin\components\Configs;
use backend\modules\admin\components\UserStatus;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 *
 * @property UserProfile $profile
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return Configs::instance()->userTable;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::class,
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'email'], 'required'],
            [['username', 'email'], 'string', 'max' => 255],
            [['username', 'email'], 'unique'],
            ['status', 'in', 'range' => [UserStatus::ACTIVE, UserStatus::INACTIVE]],
        ];
    }

    public function attributeLabels()
    {
        return [
            'username' => Yii::t('rbac-admin', 'USERNAME'),
            'email' => Yii::t('rbac-admin', 'EMAIL'),
            'status' => Yii::t('rbac-admin', 'STATUS'),
            'created_at' => Yii::t('rbac-admin', 'CREATED_AT'),
            'updated_at' => Yii::t('rbac-admin', 'UPDATED_AT'),
            'id' => 'ID'
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => UserStatus::ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        $user = static::findOne(['username' => $username, 'status' => UserStatus::ACTIVE]);
        return is_null($user) ? null : (is_null($user->admin) ? null : $user);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => UserStatus::ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int)end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @inheritdoc
     */
    public static function getDb()
    {
        return Configs::userDb();
    }

    public function getAdmin()
    {
        return $this->hasOne(Admin::class, ['uid' => 'id']);
    }

    public function getMember()
    {
        return $this->hasOne(Member::class, ['uid' => 'id']);
    }
}

backend/modules/admin/controllers/UserController.php
<?php

namespace backend\modules\admin\controllers;

use Yii;
use yii\base\InvalidArgumentException;
use yii\base\UserException;
use yii\filters\VerbFilter;
use yii\mail\BaseMailer;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use backend\modules\admin\components\UserStatus;
use backend\modules\admin\models\form\ChangePassword;
use backend\modules\admin\models\form\Login;
use backend\modules\admin\models\form\PasswordResetRequest;
use backend\modules\admin\models\form\ResetPassword;
use backend\modules\admin\models\form\Signup;
use backend\modules\admin\models\searchs\User as UserSearch;
use backend\modules\admin\models\User;

/**
 * User controller
 */
class UserController extends Controller
{
    private $_oldMailPath;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'logout' => ['post'],
                    'activate' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if (Yii::$app->has('mailer') && ($mailer = Yii::$app->getMailer()) instanceof BaseMailer) {
                /* @var $mailer BaseMailer */
                $this->_oldMailPath = $mailer->getViewPath();
                $mailer->setViewPath('@backend/modules/admin/mail');
            }
            return true;
        }
        return false;
    }

    /**
     * @inheritdoc
     */
    public function afterAction($action, $result)
    {
        if ($this->_oldMailPath !== null) {
            Yii::$app->getMailer()->setViewPath($this->_oldMailPath);
        }
        return parent::afterAction($action, $result);
    }

    /**
     * Lists all User models.
     * @param string $type
     * @return mixed
     */
    public function actionIndex($type = 'admin')
    {
        $searchModel = new UserSearch(['type' => $type]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'type' => $type
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('update', [
            'model' => $model
        ]);
    }

    public function actionProfile()
    {
        $userId = Yii::$app->user->id;
        $model = $this->findModel($userId);
        $adminModel = \backend\models\Admin::findOne(['uid' => $userId]);
        if ($adminModel === null) {
            throw new NotFoundHttpException(Yii::t('common', 'REQUESTED_PAGE_NOT_EXIST'));
        }

        if (Yii::$app->request->isPost) {
            $session = Yii::$app->session;
            $post = Yii::$app->request->post();
            if ($model->load($post) && $adminModel->load($post)) {
                $isValid = $model->validate();
                $isValid = $adminModel->validate() && $isValid;
                if ($isValid && $model->save(false) && $adminModel->save(false)) {
                    $session->setFlash('success', Yii::t('common', 'SAVE_SUCCESS'));
                } else {
                    $session->setFlash('error', Yii::t('common', 'SAVE_FAILED'));
                }
            }
        }
        return $this->render('profile', ['model' => $model, 'adminModel' => $adminModel]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->id == $id) {
            Yii::$app->session->setFlash('error', Yii::t('rbac-admin', 'CANNOT_DELETE_SELF'));
        } else {
            exit;
            $this->findModel($id)->delete();
        }
        return $this->redirect(['index']);
    }

    /**
     * Login
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new Login();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->renderPartial('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->getUser()->logout();

        return $this->goHome();
    }

    /**
     * Signup new user
     * @return string
     */
    public function actionSignup()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new Signup();
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($model->signup()) {
                return $this->goHome();
            }
        }

        return $this->renderPartial('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Request reset password
     * @return string
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequest();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->renderPartial('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Reset password
     * @return string
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPassword($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->getRequest()->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Reset password
     * @return string
     */
    public function actionChangePassword()
    {
        $model = new ChangePassword();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->change()) {
            return $this->goHome();
        }

        return $this->render('change-password', [
            'model' => $model,
        ]);
    }

    /**
     * Activate new user
     * @param integer $id
     * @return type
     * @throws UserException
     * @throws NotFoundHttpException
     */
    public function actionActivate($id)
    {
        /* @var $user User */
        $user = $this->findModel($id);
        if ($user->status == UserStatus::INACTIVE) {
            $user->status = UserStatus::ACTIVE;
            if ($user->save()) {
                return $this->redirect(['view', 'id' => $id]);
            } else {
                $errors = $user->firstErrors;
                throw new UserException(reset($errors));
            }
        }
        return $this->redirect(['view', 'id' => $id]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('common', 'REQUESTED_PAGE_NOT_EXIST'));
        }
    }
}

backend/modules/admin/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\admin\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('rbac-admin', 'USER_CREATE') : Yii::t('rbac-admin', 'USER_UPDATE'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/admin/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\components\Icon;

/* @var $this \yii\web\View */
/* @var $model \backend\modules\admin\models\searchs\User */
/* @var $type */

$this->registerJs('$(\'[data-toggle="tooltip"]\').tooltip({trigger: \'hover\'});');
$typeList = [
    'admin' => Yii::t('rbac-admin', 'TYPE_ADMIN_LABEL'),
    'member' => Yii::t('rbac-admin', 'TYPE_MEMBER_LABEL')
];
?>
<div class="user-search">
    <div class="btn-group pull-left" style="margin-right: 5px;">
        <?= Html::button($typeList[$type] . ' ' . Html::tag('span', '', ['class' => 'caret']), [
            'class' => 'btn btn-default dropdown-toggle',
            'data-toggle' => 'dropdown',
            'aria-haspopup' => 'true',
            'aria-expanded' => 'false'
        ]) ?>

        <ul class="dropdown-menu">
            <?php
            foreach ($typeList as $key => $value) {
                $activeOptions = $key == $type ? ['class' => 'active'] : [];
                echo Html::tag('li', Html::a($value, ['index', 'type' => $key]), $activeOptions);
            }
            ?>
        </ul>
    </div>
    <?php
    $form = ActiveForm::begin([
        'action' => ['index', 'type' => $type],
        'method' => 'get',
        'layout' => 'inline',
        'fieldConfig' => [
            'labelOptions' => [
                'class' => 'sr-only'
            ]
        ]
    ]);
    ?>
    <?php
    $button = Html::submitButton(Icon::i('fa-search'), [
        'class' => 'btn btn-default',
        'title' => Yii::t('common', 'SEARCH'),
        'data-toggle' => 'tooltip'
    ]);
    $addon = Html::tag('span', $button, ['class' => 'input-group-btn']);
    $searchInputTemplate = Html::tag('div', '{input}' . $addon, ['class' => 'input-group']);
    ?>
    <?=
    $form->field($model, 'username', [
        'inputOptions' => [
            'title' => Yii::t('rbac-admin', 'SEARCH_USERNAME'),
            'placeholder' => Yii::t('common', 'SEARCH'),
            'data-toggle' => 'tooltip'
        ],
        'inputTemplate' => $searchInputTemplate,
    ])->textInput(['maxlength' => true])
    ?>
    <?=
    $form->field($model, 'limit', [
        'options' => [
            'class' => 'form-group pull-right'
        ]
    ])->dropDownList([
        '5' => '5', '15' => '15', '20' => '20',
        '30' => '30', '50' => '50', '100' => '100',
        '0' => Yii::t('common', 'ALL')
    ])
    ?>
    <?php ActiveForm::end(); ?>
</div>

backend/modules/admin/views/user/change-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \backend\modules\admin\models\form\ChangePassword */

$this->title = Yii::t('rbac-admin', 'CHANGE_PASSWORD');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-change']); ?>
                <?= $form->field($model, 'oldPassword')->passwordInput() ?>
                <?= $form->field($model, 'newPassword')->passwordInput() ?>
                <?= $form->field($model, 'retypePassword')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('rbac-admin', 'SUBMIT'), [
                        'class' => 'btn btn-primary',
                        'name' => 'change-button'
                    ]) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/modules/admin/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use backend\modules\admin\components\Helper;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\admin\models\searchs\User */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $type */

$this->title = Yii::t('rbac-admin', 'USERS');
$this->params['breadcrumbs'][] = $this->title;
$this->params['active'] = 'user';
?>
<div class="user-index">
    <?= $this->render('_search', ['model' => $searchModel, 'type' => $type]); ?>
    <?=
    GridView::widget([
        'options' => ['class' => 'grid-view table-responsive'],
        'layout' => '{items}{summary}{pager}',
        'tableOptions' => ['class' => 'table table-striped table-hover'],
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'username',
            'email:email',
            'updated_at:datetime',
            'created_at:datetime',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return Yii::t('rbac-admin', $model->status == 0 ? 'INACTIVE' : 'ACTIVE');
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => Helper::filterActionColumn(['view', 'activate', 'delete']),
                'buttons' => [
                    'activate' => function ($url, $model) {
                        if ($model->status == 10) {
                            return '';
                        }
                        $options = [
                            'title' => Yii::t('rbac-admin', 'ACTIVATE'),
                            'aria-label' => Yii::t('rbac-admin', 'ACTIVATE'),
                            'data-confirm' => Yii::t('rbac-admin', 'ACTIVATE_CONFIRM'),
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];
                        return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, $options);
                    }
                ]
            ],
        ],
    ]);
    ?>
</div>

backend/modules/admin/views/user/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\components\Helper;
use backend\themes\basic\assets\AppAsset;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \backend\modules\admin\models\form\Login */

AppAsset::register($this);
(new AppAsset(['sourcePath' => '@backend/modules/admin/assets']))->addCss('main.css', true, '');

$appName = Yii::t('common', 'APP_NAME');
$client = Yii::t('common', strtoupper(Helper::getClient()));

$this->beginPage();
?>
<!doctype html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode(Yii::t('rbac-admin', 'LOGIN')) ?> - <?= $appName ?> - <?= $client ?></title>
    <?php $this->head() ?>

</head>
<body>
<?php $this->beginBody() ?>
<div class="container-fluid site-login">

    <p class="text-center"><?= Yii::t('rbac-admin', 'USER_LOGIN_FORM_HEAD') ?></p>

    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <?= $form->field($model, 'username') ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <?= $form->field($model, 'rememberMe')->checkbox() ?>
            <div style="color:#999;margin:1em 0">
                <?= Yii::t('rbac-admin', 'USER_RESET_PASSWORD_AND_SIGNUP', [
                    'reset' => Html::a(Yii::t('rbac-admin', 'RESET_IT'), ['user/request-password-reset']),
                    'signup' => Html::a(Yii::t('rbac-admin', 'SIGNUP'), ['user/signup'])
                ]) ?>
            </div>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('rbac-admin', 'LOGIN'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/modules/admin/views/user/profile.php
<?php

use yii\bootstrap\Html;
use yii\bootstrap\ActiveForm;

/* @var $this \yii\web\View */
/* @var $model \backend\modules\admin\models\User */
/* @var $adminModel \backend\models\Admin */

$this->title = Yii::t('site', 'EDIT_PROFILE');
$this->params['breadcrumbs'][] = ['label' => Yii::t('rbac-admin', 'USERS'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['active'] = 'user';

$formatter = Yii::$app->formatter;
?>
<div class="user-profile">
    <div class="btn-toolbar">
        <?= Html::a(Yii::t('rbac-admin', 'CHANGE_PASSWORD'), ['change-password'], ['class' => 'btn btn-primary btn-sm']) ?>
    </div>
    <hr>
    <?php
    $form = ActiveForm::begin([
        'id' => 'user_form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'horizontalCssClasses' => [
                'label' => 'col-lg-2',
                'hint' => 'col-lg-4'
            ]
        ]
    ])
    ?>

    <?= $form->field($adminModel, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'email')->input('email', ['maxlength' => true]) ?>
    <?= $form->field($model, 'created_at')->textInput([
        'value' => $formatter->asDatetime($model->created_at),
        'disabled' => true
    ]) ?>
    <?= $form->field($adminModel, 'lastvisitDate')->textInput([
        'value' => $formatter->asDatetime($adminModel->lastvisitDate),
        'disabled' => true
    ]) ?>
    <?= $form->field($model, 'status')->dropDownList([
        0 => Yii::t('rbac-admin', 'INACTIVE'),
        10 => Yii::t('rbac-admin', 'ACTIVATE')
    ], ['disabled' => true]) ?>
    <?= $form->field($model, 'id')->input('number', ['disabled' => true]) ?>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?= Html::submitButton(Yii::t('common', 'SAVE'), ['class' => 'btn btn-success']) ?>
            <?= Html::resetButton(Yii::t('common', 'RESET'), ['class' => 'btn btn-default']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>